### PR TITLE
Feature/3748 update themes and calendar

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-3748.

#### Changes proposed in this Pull Request:

- Update themes to work with mui5 updates

#### To Test:

- clone repo
- run `yarn && yarn start`
- Browse all of the themes (triple-click the header to toggle the global theme easily) to ensure all of the elements affected by holiday themes look as they should, including:
	- graphics
	- drawer
	- FAB
	- banners
	- code blocks
	- custom components (resources, roadmap)
	- etc.

### CODE REVIEW

**Comment by huayunh** [comment]
- [ ] Can you make dark theme [developer resources page](https://blui-doc-it--pr659-feature-3748-update-b0bxt53n.web.app/resources/developer) look closer to what's on the dev branch?
  - [ ] Mid autumn festival, developer resources page's secondary app style is incorrect (incorrect on the dev branch too, sadly)
- [ ] Right now there is a mix of ALL CAPS and unset for the button text cases across all themes

**Comment by daileytj** [comment]
mid-autumn-festival 
Screen Shot 2023-03-16 at 1 18 42 PM

**Comment by daileytj** [comment]
@huayunh I'm thinking the button style thing is out of scope here and potentially an issue with the core themes. Would you mind pointing out where some of these discrepancies are? Screenshots of the different text cases would help greatly.

**Comment by huayunh** [comment]
image
image
image
image

**Comment by daileytj** [comment]
Ahha... I see what you mean @huayunh, thanks!

**Comment by huayunh** [comment]
Do we need to log any issues in React themes about this all caps thing?

**Comment by huayunh** [comment]
I see this in the blue dark theme
image

**Comment by huayunh** [comment]
Everything else looks good to me.

**Review by JeffGreiner-eaton — APPROVED** [review]
looks good except for last comment on icon download side-drawer.

**Comment by daileytj** [comment]
> Do we need to log any issues in React themes about this all caps thing?

I don't think so. I think this is a result of certain overrides that ended up reverting things back to default rather than the blui theme.

**Comment by daileytj** [comment]
> I see this in the blue dark theme image

This looks to be an issue in the core theme. Do we want to add a patch to the doc-it blueDark theme temporarily just to have it or do we want to just fix this upstream in the darkTheme?

**Review by andrupu — APPROVED** [review]

**Review by huayunh — APPROVED** [review]

**Pull request merged**
