### PR TITLE
Bugfix/597 4123 update developer resources

### LINKED ISSUE #597: Dev resources list outdated
#### Describe the bug
https://brightlayer-ui.github.io/resources/developer 

- This page includes the wrong links to the symbols repo.
- We should also remove deprecated resources (js CLI templates, visualizations, storybook themes)
- And include React Native CLI templates in the lists... somehow it has never been included

#### Suggested fix

Update these list items to point to their proper CI build page:
- @brightlayer-ui/symbols-mui
- @brightlayer-ui/symbols
Talking about this:
image

Remove:
- @brightlayer-ui/storybook-themes
- Everything in the "Visualizations" bucket
- Everything in the "CLI Templates" bucket without a `-typescript` suffix in the package name, such as `@brightlayer-ui/cra-template-routing`

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes #597 #664 

#### Changes proposed in this Pull Request:

- Updated github repo links in developer resource page for icons and symbols, colors repo

#### Screenshots / Screen Recording (if applicable)
https://user-images.githubusercontent.com/120575281/234545445-312b563f-ecc1-447f-8a0f-5e04a8027414.mov

#### To Test:

- yarn start
- Go to Development Resouces
- Click on Github buttons of:
@brightlayer-ui/icons
@brightlayer-ui/icons-svg
@brightlayer-ui/icons-mui
@brightlayer-ui/symbols-mui
@brightlayer-ui/colors-branding

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by huayunh** [comment]
Suraj, the way our current CI tagging is set up is allowing **only** branches named `bug/xxxx` to be tagged `brightlayer-ui`. Please remember to stick to our convention next time.

**Comment by surajeaton** [comment]
> Suraj, the way our current CI tagging is set up is allowing **only** branches named `bug/xxxx` to be tagged `brightlayer-ui`. Please remember to stick to our convention next time.

Sure @huayunh Thanks.

**Review by huayunh — COMMENTED** [review]
- The `@brightlayer-ui/symbols` should point to the `/symbols` folder in the `blui-symbols` repo

The following have similar issues and shall be fairly easily addressed with your `workspace` prop:
- @brightlayer-ui/ng-progress-icons
- @brightlayer-ui/react-progress-icons
- @brightlayer-ui/react-native-progress-icons
- @brightlayer-ui/colors
- @brightlayer-ui/eslint-config
- @brightlayer-ui/prettier-config
- (The CLI templates have similar problems, but I find the root readme written a lot better than the readmes in their respective folders)

**Comment by surajeaton** [comment]
> * The `@brightlayer-ui/symbols` should point to the `/symbols` folder in the `blui-symbols` repo
> 
> The following have similar issues and shall be fairly easily addressed with your `workspace` prop:
> 
> * @brightlayer-ui/ng-progress-icons
> * @brightlayer-ui/react-progress-icons
> * @brightlayer-ui/react-native-progress-icons
> * @brightlayer-ui/colors
> * @brightlayer-ui/eslint-config
> * @brightlayer-ui/prettier-config
> * (The CLI templates have similar problems, but I find the root readme written a lot better than the readmes in their respective folders)

I will update the cli template links, as it makes more sense to point to the respective directories.

**Comment by surajeaton** [comment]
@huayunh Updated. Please review.

**Review by huayunh — APPROVED** [review]

**Pull request merged**
