### PR TITLE
Moved info for Yazad Sidhwa and Raghavendran Chithirarajan from 'curr…

### PR DESCRIPTION
**Pull request by aubreyhthompson**
Moved info for Yazad Sidhwa and Raghaverarajan Chithirarajan from 'current maintainers' to 'other contributors'

Fixes # .

#### Changes proposed in this Pull Request:

- Removed Yazad S., Tom D., and Raghaverarajan C. from Current Maintainers section
- Added them to Other Contributors section
- Removed credit imports from currentMaintainers.ts, added imports to contributors.ts
- Added Aubrey T., Arshdeep S., and Andrew P. to Current Maintainers section

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by huayunh** [comment]
I recommend adding @andrupu to the current contributors list too (Joe forgot to include him in the story description). May need to ping them and see if you can get their bios and profile pics (optional).

**Comment by huayunh** [comment]
You will also want to read the continuous integration / continuous deploy checks ("CI/CD") to see whether you got everything covered or not. I see 3 "❌" in the list "Some checks were not successful". The Firebase hosting one is something we are aware of. See if you can get the other 2 checks turning into "✔️" instead.

**Review by surajeaton — COMMENTED** [review]
Prettier is failing.

**Review by surajeaton — COMMENTED** [review]
Please run `yarn precommit`

**Review by huayunh — CHANGES_REQUESTED** [review]
I DM'd my PR comments

**Review by huayunh — APPROVED** [review]
you did it!

**Pull request merged**
